SET
REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE MEMBER RESTART IDENTITY;
TRUNCATE TABLE POST RESTART IDENTITY;
TRUNCATE TABLE POST_IMAGE RESTART IDENTITY;
TRUNCATE TABLE FOLLOW RESTART IDENTITY;
SET
REFERENTIAL_INTEGRITY TRUE;
